### ISSUE TITLE
Failure symbol

### ISSUE THREAD

**Issue by FasterThanLlamas** [jagajithmk/SubmitButton#3]
Failure state is showing a . in the middle of the button rather than an x.

<img width="204" alt="screen shot 2017-08-29 at 7 03 27 am" src="https://user-images.githubusercontent.com/19563780/29825110-3193e26e-8c88-11e7-9f10-8202b776be1c.png">

**Comment by ekdysis** [comment]
Steps to replicate error? @FasterThanLlamas

**Comment by FasterThanLlamas** [comment]
Calling         
```
submitFreezerButton.taskCompletion { (_) in
            self.submitFreezerButton.completeAnimation(status: .failed)
            
        }
```
for
`    
@IBOutlet weak var submitFreezerButton: SubmitButton!
`

**Comment by ekdysis** [comment]
@FasterThanLlamas 

Remove ```weak``` from your ```@IBOutlet```, should look like this:

```@IBOutlet var submitFreezerButton: SubmitButton!```

Let me know if that ends up being a fix please, if not I will continue to investigate. 

Also what does your ```@IBAction``` look like?

This is what I did:

    @IBAction func submitFreezerButtonOnClick(_ sender: SubmitButton) {
                     
    }

**Comment by FasterThanLlamas** [comment]
Thank you so much.  Removing `weak` immediately fixed it.

If I may ask another question, I am not clear on the correct location for `submitButton.resetToReady()`.  If I call it directly below the animation, it attempts to reset while the animation is still running.  Is it possible to detect if the animation is complete and then reset the button?

**Comment by ekdysis** [comment]
@FasterThanLlamas  

Can I see a code snippet in regards to ```submitButton.resetToReady()```?

I would like to see how you've used it and how I can attempt to troubleshoot your issue.

Thanks

**Comment by FasterThanLlamas** [comment]
```
try! self.realm.write {
            self.realm.add(submissionArray)
        }
        saveBottleEntry()
            self.view.endEditing(true)
        
        submitButton.taskCompletion { (_) in
            self.submitButton.completeAnimation(status: .success)
// I have tried it here
            self.submitButton.resetToReady()
        }
// And here.  Only showing both locations as an example.  Actual code is one or the other.
            self.submitButton.resetToReady()
        } else {
        
        submitButton.taskCompletion { (_) in
            self.submitButton.completeAnimation(status: .failed)
        }
            
        }

```

**Comment by FasterThanLlamas** [comment]
The above code attempts to save to Realm on submit.  If the saving works, it shows `.success`.  If it fails, it shows `.failed`

I have placed `resetToReady()` in each of the two locations with it not working in either.  In both cases, it attempts to display the original `"submit"` text on the button while the animation is still going.

**Comment by ekdysis** [comment]
@FasterThanLlamas 

Is this in your **ViewController.swift** file or **SubmitButton.swift** file located in your Pods?

My guess would probably be the **SubmitButton.swift** file but I don't want to assume in the event that it happens to be elsewhere.

**Comment by FasterThanLlamas** [comment]
It's in **ViewController.swift** in the `@IBAction func` for the button.

**Comment by ekdysis** [comment]
Okay let me have a look @FasterThanLlamas

**Comment by SwiftisLife** [comment]
What version of **Realm** are you using?

**Comment by FasterThanLlamas** [comment]
2.10

**Comment by FasterThanLlamas** [comment]
Hi @SwiftisLife just checking if you've had a chance to look at the `resetToReady()` yet.

Thanks!

**Comment by ekdysis** [comment]
@FasterThanLlamas Yeah I've definitely had a chance to look at it but I'm still actively working on it. Sorry for the delayed response, I've been traveling for business.

Are you close to a solution? If so, post your code.

Thanks! 👍
